// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_AwWB6Y2S1h9zlAojwmIbn2jLiewvkcA',
    appId: '1:706570566853:web:a29988e7503d94ca8b44ac',
    messagingSenderId: '706570566853',
    projectId: 'portfolio-flyboy',
    authDomain: 'portfolio-flyboy.firebaseapp.com',
    databaseURL: 'https://portfolio-flyboy-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'portfolio-flyboy.appspot.com',
    measurementId: 'G-RF84WQ9HEX',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNpjrRWlql_8WTwZrQOIc2Oj2GBlxs_PE',
    appId: '1:706570566853:ios:49ac7d4e9ea521298b44ac',
    messagingSenderId: '706570566853',
    projectId: 'portfolio-flyboy',
    databaseURL: 'https://portfolio-flyboy-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'portfolio-flyboy.appspot.com',
    iosBundleId: 'com.example.yelwinoo',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM_086IjQtcJBTnZSztiu41Iw2TOAt6m8',
    appId: '1:706570566853:android:c7aaee1c918b3b118b44ac',
    messagingSenderId: '706570566853',
    projectId: 'portfolio-flyboy',
    databaseURL: 'https://portfolio-flyboy-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'portfolio-flyboy.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_AwWB6Y2S1h9zlAojwmIbn2jLiewvkcA',
    appId: '1:706570566853:web:5b95a2439e616e008b44ac',
    messagingSenderId: '706570566853',
    projectId: 'portfolio-flyboy',
    authDomain: 'portfolio-flyboy.firebaseapp.com',
    databaseURL: 'https://portfolio-flyboy-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'portfolio-flyboy.appspot.com',
    measurementId: 'G-M1P16XHK96',
  );

}